// This file is auto-generated by Lovable. Do not modify it.

import { createLovableAuth } from "@lovable.dev/cloud-auth-js";
import { supabase } from "../supabase/client";
// oauthBrokerUrl mặc định là "/~oauth/initiate" (đường dẫn tương đối) — chỉ hoạt động
// khi app được phục vụ sau hạ tầng Lovable. Khi deploy độc lập ra Vercel, đường dẫn này
// không tồn tại nên bị 404. Trỏ thẳng về domain broker công khai của Lovable để hoạt động
// bất kể site được lưu trữ ở đâu.
const lovableAuth = createLovableAuth({
  oauthBrokerUrl: "https://oauth.lovable.app/~oauth/initiate",
});

type SignInOptions = {
  redirect_uri?: string;
  extraParams?: Record<string, string>;
};

export const lovable = {
  auth: {
    signInWithOAuth: async (
      provider: "google" | "apple" | "microsoft" | "lovable",
      opts?: SignInOptions,
    ) => {
      const result = await lovableAuth.signInWithOAuth(provider, {
        redirect_uri: opts?.redirect_uri ?? window.location.origin,
        extraParams: {
          ...opts?.extraParams,
        },
      });

      if (result.redirected) {
        return result;
      }

      if (result.error) {
        return result;
      }

      try {
        await supabase.auth.setSession(result.tokens);
      } catch (e) {
        return { error: e instanceof Error ? e : new Error(String(e)) };
      }
      return result;
    },
  },
};
