/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ChinhSachRouteImport } from './routes/chinh-sach'
import { Route as DatLichRouteImport } from './routes/dat-lich'
import { Route as GioHangRouteImport } from './routes/gio-hang'
import { Route as GioiThieuRouteImport } from './routes/gioi-thieu'
import { Route as LienHeRouteImport } from './routes/lien-he'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ThanhToanRouteImport } from './routes/thanh-toan'
import { Route as ThuArRouteImport } from './routes/thu-ar'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedQuanTriRouteImport } from './routes/_authenticated/quan-tri'
import { Route as AuthenticatedTaiKhoanRouteImport } from './routes/_authenticated/tai-khoan'
import { Route as SanPhamIndexRouteImport } from './routes/san-pham.index'
import { Route as SanPhamSlugRouteImport } from './routes/san-pham.$slug'
import { Route as SuKienIndexRouteImport } from './routes/su-kien.index'
import { Route as SuKienSlugRouteImport } from './routes/su-kien.$slug'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ChinhSachRoute = ChinhSachRouteImport.update({
  id: '/chinh-sach',
  path: '/chinh-sach',
  getParentRoute: () => rootRouteImport,
} as any)
const DatLichRoute = DatLichRouteImport.update({
  id: '/dat-lich',
  path: '/dat-lich',
  getParentRoute: () => rootRouteImport,
} as any)
const GioHangRoute = GioHangRouteImport.update({
  id: '/gio-hang',
  path: '/gio-hang',
  getParentRoute: () => rootRouteImport,
} as any)
const GioiThieuRoute = GioiThieuRouteImport.update({
  id: '/gioi-thieu',
  path: '/gioi-thieu',
  getParentRoute: () => rootRouteImport,
} as any)
const LienHeRoute = LienHeRouteImport.update({
  id: '/lien-he',
  path: '/lien-he',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ThanhToanRoute = ThanhToanRouteImport.update({
  id: '/thanh-toan',
  path: '/thanh-toan',
  getParentRoute: () => rootRouteImport,
} as any)
const ThuArRoute = ThuArRouteImport.update({
  id: '/thu-ar',
  path: '/thu-ar',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedQuanTriRoute = AuthenticatedQuanTriRouteImport.update({
  id: '/quan-tri',
  path: '/quan-tri',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTaiKhoanRoute = AuthenticatedTaiKhoanRouteImport.update({
  id: '/tai-khoan',
  path: '/tai-khoan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const SanPhamIndexRoute = SanPhamIndexRouteImport.update({
  id: '/san-pham/',
  path: '/san-pham/',
  getParentRoute: () => rootRouteImport,
} as any)
const SanPhamSlugRoute = SanPhamSlugRouteImport.update({
  id: '/san-pham/$slug',
  path: '/san-pham/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SuKienIndexRoute = SuKienIndexRouteImport.update({
  id: '/su-kien/',
  path: '/su-kien/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuKienSlugRoute = SuKienSlugRouteImport.update({
  id: '/su-kien/$slug',
  path: '/su-kien/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chinh-sach': typeof ChinhSachRoute
  '/dat-lich': typeof DatLichRoute
  '/gio-hang': typeof GioHangRoute
  '/gioi-thieu': typeof GioiThieuRoute
  '/lien-he': typeof LienHeRoute
  '/mcp': typeof McpRoute
  '/thanh-toan': typeof ThanhToanRoute
  '/thu-ar': typeof ThuArRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/quan-tri': typeof AuthenticatedQuanTriRoute
  '/tai-khoan': typeof AuthenticatedTaiKhoanRoute
  '/san-pham/$slug': typeof SanPhamSlugRoute
  '/su-kien/$slug': typeof SuKienSlugRoute
  '/san-pham/': typeof SanPhamIndexRoute
  '/su-kien/': typeof SuKienIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chinh-sach': typeof ChinhSachRoute
  '/dat-lich': typeof DatLichRoute
  '/gio-hang': typeof GioHangRoute
  '/gioi-thieu': typeof GioiThieuRoute
  '/lien-he': typeof LienHeRoute
  '/mcp': typeof McpRoute
  '/thanh-toan': typeof ThanhToanRoute
  '/thu-ar': typeof ThuArRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/quan-tri': typeof AuthenticatedQuanTriRoute
  '/tai-khoan': typeof AuthenticatedTaiKhoanRoute
  '/san-pham/$slug': typeof SanPhamSlugRoute
  '/su-kien/$slug': typeof SuKienSlugRoute
  '/san-pham': typeof SanPhamIndexRoute
  '/su-kien': typeof SuKienIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/chinh-sach': typeof ChinhSachRoute
  '/dat-lich': typeof DatLichRoute
  '/gio-hang': typeof GioHangRoute
  '/gioi-thieu': typeof GioiThieuRoute
  '/lien-he': typeof LienHeRoute
  '/mcp': typeof McpRoute
  '/thanh-toan': typeof ThanhToanRoute
  '/thu-ar': typeof ThuArRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/quan-tri': typeof AuthenticatedQuanTriRoute
  '/_authenticated/tai-khoan': typeof AuthenticatedTaiKhoanRoute
  '/san-pham/$slug': typeof SanPhamSlugRoute
  '/su-kien/$slug': typeof SuKienSlugRoute
  '/san-pham/': typeof SanPhamIndexRoute
  '/su-kien/': typeof SuKienIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/chinh-sach'
    | '/dat-lich'
    | '/gio-hang'
    | '/gioi-thieu'
    | '/lien-he'
    | '/mcp'
    | '/thanh-toan'
    | '/thu-ar'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/quan-tri'
    | '/tai-khoan'
    | '/san-pham/$slug'
    | '/su-kien/$slug'
    | '/san-pham/'
    | '/su-kien/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/chinh-sach'
    | '/dat-lich'
    | '/gio-hang'
    | '/gioi-thieu'
    | '/lien-he'
    | '/mcp'
    | '/thanh-toan'
    | '/thu-ar'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/quan-tri'
    | '/tai-khoan'
    | '/san-pham/$slug'
    | '/su-kien/$slug'
    | '/san-pham'
    | '/su-kien'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/chinh-sach'
    | '/dat-lich'
    | '/gio-hang'
    | '/gioi-thieu'
    | '/lien-he'
    | '/mcp'
    | '/thanh-toan'
    | '/thu-ar'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/quan-tri'
    | '/_authenticated/tai-khoan'
    | '/san-pham/$slug'
    | '/su-kien/$slug'
    | '/san-pham/'
    | '/su-kien/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ChinhSachRoute: typeof ChinhSachRoute
  DatLichRoute: typeof DatLichRoute
  GioHangRoute: typeof GioHangRoute
  GioiThieuRoute: typeof GioiThieuRoute
  LienHeRoute: typeof LienHeRoute
  McpRoute: typeof McpRoute
  ThanhToanRoute: typeof ThanhToanRoute
  ThuArRoute: typeof ThuArRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  SanPhamSlugRoute: typeof SanPhamSlugRoute
  SuKienSlugRoute: typeof SuKienSlugRoute
  SanPhamIndexRoute: typeof SanPhamIndexRoute
  SuKienIndexRoute: typeof SuKienIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chinh-sach': {
      id: '/chinh-sach'
      path: '/chinh-sach'
      fullPath: '/chinh-sach'
      preLoaderRoute: typeof ChinhSachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dat-lich': {
      id: '/dat-lich'
      path: '/dat-lich'
      fullPath: '/dat-lich'
      preLoaderRoute: typeof DatLichRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gio-hang': {
      id: '/gio-hang'
      path: '/gio-hang'
      fullPath: '/gio-hang'
      preLoaderRoute: typeof GioHangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gioi-thieu': {
      id: '/gioi-thieu'
      path: '/gioi-thieu'
      fullPath: '/gioi-thieu'
      preLoaderRoute: typeof GioiThieuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lien-he': {
      id: '/lien-he'
      path: '/lien-he'
      fullPath: '/lien-he'
      preLoaderRoute: typeof LienHeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thanh-toan': {
      id: '/thanh-toan'
      path: '/thanh-toan'
      fullPath: '/thanh-toan'
      preLoaderRoute: typeof ThanhToanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thu-ar': {
      id: '/thu-ar'
      path: '/thu-ar'
      fullPath: '/thu-ar'
      preLoaderRoute: typeof ThuArRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/quan-tri': {
      id: '/_authenticated/quan-tri'
      path: '/quan-tri'
      fullPath: '/quan-tri'
      preLoaderRoute: typeof AuthenticatedQuanTriRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tai-khoan': {
      id: '/_authenticated/tai-khoan'
      path: '/tai-khoan'
      fullPath: '/tai-khoan'
      preLoaderRoute: typeof AuthenticatedTaiKhoanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/san-pham/': {
      id: '/san-pham/'
      path: '/san-pham'
      fullPath: '/san-pham/'
      preLoaderRoute: typeof SanPhamIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/san-pham/$slug': {
      id: '/san-pham/$slug'
      path: '/san-pham/$slug'
      fullPath: '/san-pham/$slug'
      preLoaderRoute: typeof SanPhamSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/su-kien/': {
      id: '/su-kien/'
      path: '/su-kien'
      fullPath: '/su-kien/'
      preLoaderRoute: typeof SuKienIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/su-kien/$slug': {
      id: '/su-kien/$slug'
      path: '/su-kien/$slug'
      fullPath: '/su-kien/$slug'
      preLoaderRoute: typeof SuKienSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedQuanTriRoute: typeof AuthenticatedQuanTriRoute
  AuthenticatedTaiKhoanRoute: typeof AuthenticatedTaiKhoanRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedQuanTriRoute: AuthenticatedQuanTriRoute,
  AuthenticatedTaiKhoanRoute: AuthenticatedTaiKhoanRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ChinhSachRoute: ChinhSachRoute,
  DatLichRoute: DatLichRoute,
  GioHangRoute: GioHangRoute,
  GioiThieuRoute: GioiThieuRoute,
  LienHeRoute: LienHeRoute,
  McpRoute: McpRoute,
  ThanhToanRoute: ThanhToanRoute,
  ThuArRoute: ThuArRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  SanPhamSlugRoute: SanPhamSlugRoute,
  SuKienSlugRoute: SuKienSlugRoute,
  SanPhamIndexRoute: SanPhamIndexRoute,
  SuKienIndexRoute: SuKienIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
