ALTER TABLE public.events ADD COLUMN IF NOT EXISTS category text;

UPDATE public.events SET category = 'TIN ƯU ĐÃI' WHERE slug = 'uu-dai-gong-0-dong' AND category IS NULL;
UPDATE public.events SET category = 'SỰ KIỆN' WHERE slug IN ('kham-mat-mien-phi-thang-8','workshop-chon-gong-theo-khuon-mat') AND category IS NULL;

INSERT INTO public.events (slug, title, category, excerpt, content, location, starts_at, ends_at, is_visible, cover_image) VALUES
('uu-dai-mua-he-di-san', 'Chương Trình Ưu Đãi Mùa Hè: Giảm 20% Bộ Sưu Tập Di Sản', 'TIN ƯU ĐÃI', 'Toàn bộ Bộ Sưu Tập Di Sản giảm 20% trong mùa hè này, kèm dịch vụ đo khúc xạ và tinh chỉnh gọng miễn phí.', 'Trong suốt tháng 7 và tháng 8, Vin Eyewear dành tặng ưu đãi 20% cho toàn bộ Bộ Sưu Tập Di Sản.\nƯu đãi áp dụng tại cả hai cơ sở, kèm dịch vụ đo khúc xạ, tinh chỉnh gọng và vệ sinh kính miễn phí trọn đời.', 'Cả 2 cơ sở Vin Eyewear', '2026-07-15 02:00:00+00', '2026-08-15 12:00:00+00', true, '/images/product-1.jpg'),
('cham-soc-kinh-nhua-nhap-khau', 'Buổi Chia Sẻ: Nghệ Thuật Chăm Sóc Và Bảo Quản Kính Nhựa Nhập Khẩu', 'SỰ KIỆN', 'Kỹ thuật viên Vin Eyewear hướng dẫn cách vệ sinh, bảo quản và phục hồi độ bóng cho gọng acetate nhập khẩu.', 'Một buổi chiều dành riêng cho những người yêu gọng acetate.\nChúng tôi chia sẻ quy trình vệ sinh chuẩn, cách tránh biến dạng gọng và mẹo giữ độ bóng bền lâu.', 'Cơ sở 46 Hoàng Hoa Thám, Tây Hồ', '2026-07-26 07:00:00+00', NULL, true, '/images/product-2.jpg'),
('ra-mat-kinh-titan-sieu-nhe', 'Ra Mắt Dòng Kính Titan Siêu Nhẹ Mới Mùa Thu 2026', 'SẢN PHẨM MỚI', 'Dòng gọng titan nguyên khối chỉ 9 gram, thiết kế tối giản dành cho người đeo kính cả ngày.', 'Bộ sưu tập titan mùa thu 2026 tập trung vào sự nhẹ nhàng gần như vô hình.\nGọng nguyên khối, khớp bản lề không ốc, hoàn thiện nhám mờ với bốn sắc độ trung tính.', 'Cả 2 cơ sở Vin Eyewear', '2026-09-05 03:00:00+00', NULL, true, '/images/product-3.jpg'),
('trien-lam-khung-kinh-qua-cac-thap-ky', 'Triển Lãm: Khung Kính Qua Các Thập Kỷ Ký Ức', 'TRIỂN LÃM', 'Hơn 60 mẫu gọng từ thập niên 1950 đến nay, kể lại lịch sử thiết kế kính mắt bằng hiện vật.', 'Triển lãm trưng bày hơn 60 mẫu gọng sưu tầm, sắp đặt theo từng thập kỷ.\nKhách tham quan có thể thử một số phiên bản phục dựng và nghe câu chuyện phía sau từng thiết kế.', 'Cơ sở 261 Ngọc Lâm, Long Biên', '2026-09-18 02:00:00+00', '2026-09-30 12:00:00+00', true, '/images/product-4.jpg'),
('kham-thi-luc-tu-van-dang-kinh', 'Chương Trình Khám Thị Lực Và Tư Vấn Dáng Kính Miễn Phí', 'SỰ KIỆN', 'Đo khúc xạ bằng thiết bị chuyên sâu và tư vấn dáng gọng theo khuôn mặt, hoàn toàn miễn phí.', 'Đội ngũ kỹ thuật viên khúc xạ của Vin Eyewear thực hiện quy trình đo 8 bước.\nSau khi đo, bạn được tư vấn dáng gọng phù hợp với tỉ lệ khuôn mặt và nhu cầu sử dụng.', 'Cả 2 cơ sở Vin Eyewear', '2026-08-20 02:00:00+00', '2026-08-31 12:00:00+00', true, '/images/product-5.jpg'),
('dem-tiec-nhuom-mau-trong-kinh', 'Đêm Tiệc Trải Nghiệm: Nhuộm Màu Tròng Kính Thủ Công', 'SỰ KIỆN', 'Tự tay chọn sắc độ và nhuộm màu tròng kính của riêng bạn cùng kỹ thuật viên Vin Eyewear.', 'Một buổi tối giới hạn 20 khách, nơi bạn tự chọn sắc độ và theo dõi toàn bộ quy trình nhuộm tròng thủ công.\nMỗi khách mang về một cặp tròng màu độc bản.', 'Cơ sở 46 Hoàng Hoa Thám, Tây Hồ', '2026-10-10 12:00:00+00', NULL, true, '/images/product-6.jpg')
ON CONFLICT (slug) DO NOTHING;